# Generated by Django 4.2.4 on 2023-09-07 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_nationality_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
