# Generated by Django 4.2.4 on 2023-09-07 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
