# Generated by Django 4.2.7 on 2023-11-24 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitting', '0011_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='repost',
            field=models.ManyToManyField(blank=True, related_name='comment_reposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
